name: flutter_adcontent
description: "一款优质的穿山甲内容输出插件，支持「短剧」和「小视频」"
version: 0.0.2
homepage: https://flutterads.github.io/site/
repository: https://github.com/FlutterAds/flutter_adcontent

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_adcontent
        pluginClass: FlutterAdcontentPlugin
      ios:
        pluginClass: FlutterAdcontentPlugin
