name: flutter_adcontent
description: "一款优质的穿山甲内容输出插件，支持「短剧」和「小视频」"
version: 1.1.0
repository: https://github.com/FlutterAds/flutter_adcontent
issue_tracker: https://github.com/FlutterAds/flutter_adcontent/issues
homepage: https://flutterads.top
documentation: https://flutterads.top/start/guide/adcontent/install.html
topics: [flutterads, ads, gromore, adcontent, income]
funding: [https://github.com/FlutterAds/.github]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_adcontent
        pluginClass: FlutterAdcontentPlugin
      ios:
        pluginClass: FlutterAdcontentPlugin
